/**
 * AlmaMundi — historias mock narrativas (demo 2–12 por formato)
 * Formato: StoryPoint (compatible con lib/map-data/stories)
 *
 * Se fusionan en lib/demo-video-stories.ts y lib/historias/historias-demo-stories.ts
 */
import type { StoryPoint } from '@/lib/map-data/stories';

// ─── VIDEOS ──────────────────────────────────────────────────────────────────

export const DEMO_VIDEO_STORIES_EXTRA: StoryPoint[] = [
  {
    id: 'demo-video-2',
    lat: -33.4489,
    lng: -70.6693,
    label: 'El último verano en la casa grande',
    title: 'El último verano en la casa grande',
    subtitle: 'Santiago, antes de la demolición',
    authorName: 'Valentina Cruz',
    author: { name: 'Valentina Cruz', avatar: 'https://i.pravatar.cc/150?img=5' },
    city: 'Santiago',
    country: 'Chile',
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    thumbnailUrl: 'https://picsum.photos/seed/am-v2/1920/1080',
    hasVideo: true,
    publishedAt: '2026-01-01T12:00:00.000Z',
    tags: ['memoria', 'familia', 'ciudad'],
    quote: 'Vendimos la casa en marzo. Grabé cada habitación antes de irnos.',
    isDemo: true,
  },
  {
    id: 'demo-video-3',
    lat: 19.4326,
    lng: -99.1332,
    label: 'Mi abuela bailando sola en la cocina',
    title: 'Mi abuela bailando sola en la cocina',
    subtitle: 'Ciudad de México, un martes cualquiera',
    authorName: 'Rodrigo Fuentes',
    author: { name: 'Rodrigo Fuentes', avatar: 'https://i.pravatar.cc/150?img=11' },
    city: 'Ciudad de México',
    country: 'México',
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    thumbnailUrl: 'https://picsum.photos/seed/am-v3/1920/1080',
    hasVideo: true,
    publishedAt: '2026-01-02T12:00:00.000Z',
    tags: ['familia', 'memoria', 'amor'],
    quote: 'Tenía 84 años y bailaba cumbia. No sabía que la estaba grabando.',
    isDemo: true,
  },
  {
    id: 'demo-video-4',
    lat: -39.8142,
    lng: -73.2459,
    label: 'El río que ya no existe',
    title: 'El río que ya no existe',
    subtitle: 'Valdivia, diez años después',
    authorName: 'Camila Herrera',
    author: { name: 'Camila Herrera', avatar: 'https://i.pravatar.cc/150?img=9' },
    city: 'Valdivia',
    country: 'Chile',
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    thumbnailUrl: 'https://picsum.photos/seed/am-v4/1920/1080',
    hasVideo: true,
    publishedAt: '2026-01-03T12:00:00.000Z',
    tags: ['naturaleza', 'memoria', 'pérdida'],
    quote: 'El río donde aprendí a nadar se había secado. Grabé el cauce vacío.',
    isDemo: true,
  },
  {
    id: 'demo-video-5',
    lat: 52.52,
    lng: 13.405,
    label: 'Primera nevada en Berlín',
    title: 'Primera nevada en Berlín',
    subtitle: 'Berlín, enero de 2026',
    authorName: 'María José Pinto',
    author: { name: 'María José Pinto', avatar: 'https://i.pravatar.cc/150?img=16' },
    city: 'Berlín',
    country: 'Alemania',
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    thumbnailUrl: 'https://picsum.photos/seed/am-v5/1920/1080',
    hasVideo: true,
    publishedAt: '2026-01-04T12:00:00.000Z',
    tags: ['migración', 'identidad', 'naturaleza'],
    quote: 'Lloré de frío y de asombro al mismo tiempo.',
    isDemo: true,
  },
  {
    id: 'demo-video-6',
    lat: -13.532,
    lng: -71.9675,
    label: 'El mercado de mi madre',
    title: 'El mercado de mi madre',
    subtitle: 'Cusco, treinta años en el mismo puesto',
    authorName: 'Isabel Quispe',
    author: { name: 'Isabel Quispe', avatar: 'https://i.pravatar.cc/150?img=21' },
    city: 'Cusco',
    country: 'Perú',
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    thumbnailUrl: 'https://picsum.photos/seed/am-v6/1920/1080',
    hasVideo: true,
    publishedAt: '2026-01-05T12:00:00.000Z',
    tags: ['familia', 'trabajo', 'cuidado'],
    quote: 'Mi madre lleva treinta años en el mismo puesto. Este es un día normal con ella.',
    isDemo: true,
  },
  {
    id: 'demo-video-7',
    lat: -34.9011,
    lng: -56.1645,
    label: 'Papá aprendiendo a usar el celular',
    title: 'Papá aprendiendo a usar el celular',
    subtitle: 'Montevideo, mensajes para los nietos',
    authorName: 'Diego Morales',
    author: { name: 'Diego Morales', avatar: 'https://i.pravatar.cc/150?img=33' },
    city: 'Montevideo',
    country: 'Uruguay',
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    thumbnailUrl: 'https://picsum.photos/seed/am-v7/1920/1080',
    hasVideo: true,
    publishedAt: '2026-01-06T12:00:00.000Z',
    tags: ['familia', 'tiempo', 'amor'],
    quote: 'Tiene 71 años y quería mandarle mensajes de voz a sus nietos en Australia.',
    isDemo: true,
  },
  {
    id: 'demo-video-8',
    lat: 4.711,
    lng: -74.0721,
    label: 'El barrio antes de la autopista',
    title: 'El barrio antes de la autopista',
    subtitle: 'Bogotá, lo que había antes',
    authorName: 'Lucía Vargas',
    author: { name: 'Lucía Vargas', avatar: 'https://i.pravatar.cc/150?img=44' },
    city: 'Bogotá',
    country: 'Colombia',
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    thumbnailUrl: 'https://picsum.photos/seed/am-v8/1920/1080',
    hasVideo: true,
    publishedAt: '2026-01-07T12:00:00.000Z',
    tags: ['ciudad', 'memoria', 'política'],
    quote: 'Filmé cada calle del barrio dos semanas antes de las demoliciones.',
    isDemo: true,
  },
  {
    id: 'demo-video-9',
    lat: 40.4168,
    lng: -3.7038,
    label: 'El primer día de escuela en España',
    title: 'El primer día de escuela en España',
    subtitle: 'Madrid, Mateo tiene cinco años',
    authorName: 'Andrea Rojas',
    author: { name: 'Andrea Rojas', avatar: 'https://i.pravatar.cc/150?img=25' },
    city: 'Madrid',
    country: 'España',
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    thumbnailUrl: 'https://picsum.photos/seed/am-v9/1920/1080',
    hasVideo: true,
    publishedAt: '2026-01-08T12:00:00.000Z',
    tags: ['migración', 'infancia', 'familia'],
    quote: 'Llegamos de Venezuela hace dos años. Mateo no conoce a nadie.',
    isDemo: true,
  },
  {
    id: 'demo-video-10',
    lat: -23.5505,
    lng: -46.6333,
    label: 'El taller de mi abuelo',
    title: 'El taller de mi abuelo',
    subtitle: 'São Paulo, antes de vaciarlo',
    authorName: 'Tomás Medina',
    author: { name: 'Tomás Medina', avatar: 'https://i.pravatar.cc/150?img=38' },
    city: 'São Paulo',
    country: 'Brasil',
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    thumbnailUrl: 'https://picsum.photos/seed/am-v10/1920/1080',
    hasVideo: true,
    publishedAt: '2026-01-09T12:00:00.000Z',
    tags: ['familia', 'trabajo', 'pérdida'],
    quote: 'Olía a madera y a él.',
    isDemo: true,
  },
  {
    id: 'demo-video-11',
    lat: 35.7595,
    lng: -5.834,
    label: 'Cruzando el Estrecho',
    title: 'Cruzando el Estrecho',
    subtitle: 'Tánger → Algeciras, 22 minutos',
    authorName: 'Fatima El Alaoui',
    author: { name: 'Fatima El Alaoui', avatar: 'https://i.pravatar.cc/150?img=49' },
    city: 'Tánger',
    country: 'Marruecos',
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    thumbnailUrl: 'https://picsum.photos/seed/am-v11/1920/1080',
    hasVideo: true,
    publishedAt: '2026-01-10T12:00:00.000Z',
    tags: ['migración', 'valentía', 'frontera'],
    quote: 'Veintidós minutos. Los más largos de mi vida.',
    isDemo: true,
  },
  {
    id: 'demo-video-12',
    lat: -33.4489,
    lng: -70.6693,
    label: 'El último tren a Constitución',
    title: 'El último tren a Constitución',
    subtitle: 'Santiago, el fin de un recorrido',
    authorName: 'Fernanda Lagos',
    author: { name: 'Fernanda Lagos', avatar: 'https://i.pravatar.cc/150?img=36' },
    city: 'Santiago',
    country: 'Chile',
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    thumbnailUrl: 'https://picsum.photos/seed/am-v12/1920/1080',
    hasVideo: true,
    publishedAt: '2026-01-11T12:00:00.000Z',
    tags: ['ciudad', 'trabajo', 'tiempo'],
    quote: 'El tren que tomaba mi padre todos los días fue cancelado. Filmé el último viaje.',
    isDemo: true,
  },
];

// ─── AUDIOS ──────────────────────────────────────────────────────────────────

export const DEMO_AUDIO_STORIES_EXTRA: StoryPoint[] = [
  {
    id: 'demo-audio-2',
    lat: -12.0464,
    lng: -77.0428,
    label: 'El idioma que no le enseñé a mis hijos',
    title: 'El idioma que no le enseñé a mis hijos',
    subtitle: 'Lima, quechua que se fue',
    authorName: 'Ana Quispe',
    author: { name: 'Ana Quispe', avatar: 'https://i.pravatar.cc/150?img=32' },
    city: 'Lima',
    country: 'Perú',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3',
    thumbnailUrl: 'https://picsum.photos/seed/am-a2/800/800',
    hasAudio: true,
    publishedAt: '2026-01-12T12:00:00.000Z',
    tags: ['identidad', 'familia', 'pérdida'],
    quote: 'A veces pienso que les robé algo al no enseñárselo.',
    isDemo: true,
  },
  {
    id: 'demo-audio-3',
    lat: 3.848,
    lng: -77.0428,
    label: 'La canción que mi padre nunca terminó',
    title: 'La canción que mi padre nunca terminó',
    subtitle: 'Cali, una melodía de su juventud',
    authorName: 'Jorge Reyes',
    author: { name: 'Jorge Reyes', avatar: 'https://i.pravatar.cc/150?img=15' },
    city: 'Cali',
    country: 'Colombia',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3',
    thumbnailUrl: 'https://picsum.photos/seed/am-a3/800/800',
    hasAudio: true,
    publishedAt: '2026-01-13T12:00:00.000Z',
    tags: ['familia', 'música', 'memoria'],
    quote: 'Nunca supo el nombre. Yo tampoco.',
    isDemo: true,
  },
  {
    id: 'demo-audio-4',
    lat: 17.0732,
    lng: -96.7266,
    label: 'Voces del mercado de Oaxaca',
    title: 'Voces del mercado de Oaxaca',
    subtitle: 'Oaxaca, un martes por la mañana',
    authorName: 'Sofía Mendoza',
    author: { name: 'Sofía Mendoza', avatar: 'https://i.pravatar.cc/150?img=23' },
    city: 'Oaxaca',
    country: 'México',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3',
    thumbnailUrl: 'https://picsum.photos/seed/am-a4/800/800',
    hasAudio: true,
    publishedAt: '2026-01-14T12:00:00.000Z',
    tags: ['ciudad', 'cotidiano', 'comunidad'],
    quote: 'Nada especial. Todo especial.',
    isDemo: true,
  },
  {
    id: 'demo-audio-5',
    lat: -33.4489,
    lng: -70.6693,
    label: 'Mi madre rezando antes de dormir',
    title: 'Mi madre rezando antes de dormir',
    subtitle: 'Santiago, el ritual de cada noche',
    authorName: 'Pilar Castillo',
    author: { name: 'Pilar Castillo', avatar: 'https://i.pravatar.cc/150?img=41' },
    city: 'Santiago',
    country: 'Chile',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3',
    thumbnailUrl: 'https://picsum.photos/seed/am-a5/800/800',
    hasAudio: true,
    publishedAt: '2026-01-15T12:00:00.000Z',
    tags: ['familia', 'fe', 'memoria'],
    quote: 'Siempre rezaba en voz baja. Nunca le pregunté a quién.',
    isDemo: true,
  },
  {
    id: 'demo-audio-6',
    lat: -39.8142,
    lng: -73.2459,
    label: 'El sonido de la lluvia en Valdivia',
    title: 'El sonido de la lluvia en Valdivia',
    subtitle: 'Valdivia, abril de 2026',
    authorName: 'Martín Soto',
    author: { name: 'Martín Soto', avatar: 'https://i.pravatar.cc/150?img=52' },
    city: 'Valdivia',
    country: 'Chile',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3',
    thumbnailUrl: 'https://picsum.photos/seed/am-a6/800/800',
    hasAudio: true,
    publishedAt: '2026-01-16T12:00:00.000Z',
    tags: ['naturaleza', 'memoria', 'lugar'],
    quote: 'La lluvia era constante, molesta, hermosa.',
    isDemo: true,
  },
  {
    id: 'demo-audio-7',
    lat: 32.6996,
    lng: -115.4985,
    label: 'La primera llamada desde el otro lado',
    title: 'La primera llamada desde el otro lado',
    subtitle: 'Mexicali, solo dijo: llegué',
    authorName: 'Rosa Núñez',
    author: { name: 'Rosa Núñez', avatar: 'https://i.pravatar.cc/150?img=29' },
    city: 'Mexicali',
    country: 'México',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-7.mp3',
    thumbnailUrl: 'https://picsum.photos/seed/am-a7/800/800',
    hasAudio: true,
    publishedAt: '2026-01-17T12:00:00.000Z',
    tags: ['migración', 'familia', 'frontera'],
    quote: 'Guardé ese mensaje nueve años.',
    isDemo: true,
  },
  {
    id: 'demo-audio-8',
    lat: -34.6037,
    lng: -58.3816,
    label: 'Cuéntame de cuando eras joven',
    title: 'Cuéntame de cuando eras joven',
    subtitle: 'Buenos Aires, tres horas de historia',
    authorName: 'Elena Fuentes',
    author: { name: 'Elena Fuentes', avatar: 'https://i.pravatar.cc/150?img=18' },
    city: 'Buenos Aires',
    country: 'Argentina',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3',
    thumbnailUrl: 'https://picsum.photos/seed/am-a8/800/800',
    hasAudio: true,
    publishedAt: '2026-01-18T12:00:00.000Z',
    tags: ['memoria', 'historia', 'familia'],
    quote: 'Un domingo le pedí a mi tía de 78 años que me contara su vida.',
    isDemo: true,
  },
  {
    id: 'demo-audio-9',
    lat: -32.9442,
    lng: -60.6505,
    label: 'El ruido de la fábrica que cerró',
    title: 'El ruido de la fábrica que cerró',
    subtitle: 'Rosario, el último día',
    authorName: 'Alberto Ramos',
    author: { name: 'Alberto Ramos', avatar: 'https://i.pravatar.cc/150?img=57' },
    city: 'Rosario',
    country: 'Argentina',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-9.mp3',
    thumbnailUrl: 'https://picsum.photos/seed/am-a9/800/800',
    hasAudio: true,
    publishedAt: '2026-01-19T12:00:00.000Z',
    tags: ['trabajo', 'pérdida', 'ciudad'],
    quote: 'Trabajé veinte años ahí. Ese sonido era mi vida.',
    isDemo: true,
  },
  {
    id: 'demo-audio-10',
    lat: 4.711,
    lng: -74.0721,
    label: 'Mi hija cantando sin saber que escuchaba',
    title: 'Mi hija cantando sin saber que escuchaba',
    subtitle: 'Bogotá, un pasillo y una canción',
    authorName: 'Claudia Torres',
    author: { name: 'Claudia Torres', avatar: 'https://i.pravatar.cc/150?img=43' },
    city: 'Bogotá',
    country: 'Colombia',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-10.mp3',
    thumbnailUrl: 'https://picsum.photos/seed/am-a10/800/800',
    hasAudio: true,
    publishedAt: '2026-01-20T12:00:00.000Z',
    tags: ['familia', 'amor', 'cotidiano'],
    quote: 'Me quedé quieta en el pasillo diez minutos.',
    isDemo: true,
  },
  {
    id: 'demo-audio-11',
    lat: -34.6037,
    lng: -58.3816,
    label: 'El árabe de mi infancia',
    title: 'El árabe de mi infancia',
    subtitle: 'Buenos Aires, intentando recordar',
    authorName: 'Nadia Khalil',
    author: { name: 'Nadia Khalil', avatar: 'https://i.pravatar.cc/150?img=27' },
    city: 'Buenos Aires',
    country: 'Argentina',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-11.mp3',
    thumbnailUrl: 'https://picsum.photos/seed/am-a11/800/800',
    hasAudio: true,
    publishedAt: '2026-01-21T12:00:00.000Z',
    tags: ['identidad', 'migración', 'lengua'],
    quote: 'A los veinte ya no hablaba árabe. Este audio es yo intentando recordar.',
    isDemo: true,
  },
  {
    id: 'demo-audio-12',
    lat: -25.2867,
    lng: -57.647,
    label: 'La última conversación',
    title: 'La última conversación',
    subtitle: 'Asunción, el 14 de marzo',
    authorName: 'Miguel Ángel Vera',
    author: { name: 'Miguel Ángel Vera', avatar: 'https://i.pravatar.cc/150?img=61' },
    city: 'Asunción',
    country: 'Paraguay',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-12.mp3',
    thumbnailUrl: 'https://picsum.photos/seed/am-a12/800/800',
    hasAudio: true,
    publishedAt: '2026-01-22T12:00:00.000Z',
    tags: ['pérdida', 'familia', 'memoria'],
    quote: 'No sabía que sería la última vez. Guardé el mensaje de voz.',
    isDemo: true,
  },
];

// ─── TEXTOS ──────────────────────────────────────────────────────────────────

export const DEMO_TEXT_STORIES_EXTRA: StoryPoint[] = [
  {
    id: 'demo-texto-2',
    lat: -33.4489,
    lng: -70.6693,
    label: 'Lo que cabía en una maleta',
    title: 'Lo que cabía en una maleta',
    subtitle: 'Santiago, el día de la partida',
    authorName: 'Ana Muñoz',
    author: { name: 'Ana Muñoz', avatar: 'https://i.pravatar.cc/150?img=7' },
    city: 'Santiago',
    country: 'Chile',
    hasText: true,
    body: `Solo cabía lo esencial. Fotos, un libro, una carta que mi madre escribió y que nunca leí hasta ese día.

El resto se quedó atrás. La vajilla que compramos el primer año. La cama donde nacieron mis hijos. El jardín que planté cuando todavía creía que íbamos a quedarnos.

Hay un ejercicio que les propongo a quienes están a punto de emigrar: hagan la maleta sin pensar. Lo que elijan en ese primer instante es lo que realmente son. No lo que creen ser.

Yo elegí las fotos. Siempre supe que era mi memoria lo que necesitaba proteger.

Ahora vivo en otra ciudad con la misma maleta sobre el mismo armario. La abro una vez al año. Todo sigue ahí.`,
    excerpt:
      'Solo cabía lo esencial. Fotos, un libro, una carta que mi madre escribió y que nunca leí hasta ese día.',
    thumbnailUrl: 'https://picsum.photos/seed/am-t2/1200/800',
    publishedAt: '2026-01-23T12:00:00.000Z',
    tags: ['migración', 'memoria', 'identidad'],
    quote: 'Lo que elijan en ese primer instante es lo que realmente son.',
    isDemo: true,
  },
  {
    id: 'demo-texto-3',
    lat: 19.4326,
    lng: -99.1332,
    label: 'El día que dejé de entender a mi madre',
    title: 'El día que dejé de entender a mi madre',
    subtitle: 'Ciudad de México, la enfermedad del olvido',
    authorName: 'Ricardo Flores',
    author: { name: 'Ricardo Flores', avatar: 'https://i.pravatar.cc/150?img=13' },
    city: 'Ciudad de México',
    country: 'México',
    hasText: true,
    body: `Fue un miércoles. Me preguntó cómo me llamaba.

Llevaba cincuenta y dos años diciéndole Ricardo. Ese día me dijo que yo no podía ser Ricardo porque Ricardo era su hijo y era mucho más chico.

El Alzheimer no llega de golpe. Llega como el agua que entra por una rendija: primero no la ves, después no puedes ignorarla, después ya es demasiado tarde para ponerle algo encima.

Lo que nadie te dice es que el duelo empieza antes de la muerte. Que puedes llorar a alguien que todavía está sentado frente a ti, tomando sopa, mirándote con ojos que ya no te reconocen.

Lo que sí te queda es esto: el amor no necesita que te recuerden. Puedes amar a alguien que no sabe quién eres. Yo lo hago todos los días.`,
    excerpt: 'Fue un miércoles. Me preguntó cómo me llamaba.',
    thumbnailUrl: 'https://picsum.photos/seed/am-t3/1200/800',
    publishedAt: '2026-01-24T12:00:00.000Z',
    tags: ['cuidado', 'familia', 'pérdida'],
    quote: 'El duelo empieza antes de la muerte.',
    isDemo: true,
  },
  {
    id: 'demo-texto-4',
    lat: -34.6037,
    lng: -58.3816,
    label: 'Ser la primera de la familia en ir a la universidad',
    title: 'Ser la primera de la familia en ir a la universidad',
    subtitle: 'Buenos Aires, primera generación',
    authorName: 'Verónica Sosa',
    author: { name: 'Verónica Sosa', avatar: 'https://i.pravatar.cc/150?img=35' },
    city: 'Buenos Aires',
    country: 'Argentina',
    hasText: true,
    body: `El primer día de facultad me puse la ropa equivocada. No sé cómo explicar eso sin que suene superficial, pero es la verdad más profunda que tengo de ese día.

Nadie en mi familia había pisado una universidad. Mi madre terminó el secundario de noche, entre turno y turno. Mi padre no llegó a eso.

Entré al aula y sentí que todos sabían algo que yo no. Una clave que se transmite de padres que estudiaron a hijos que estudian. Yo no tenía esa clave.

Tardé tres años en entender que la clave no existe. Que todos estaban igual de perdidos. Que la diferencia era que ellos podían simular que no lo estaban.

Ahora soy docente. El primer día de clases siempre busco en el aula a alguien con la ropa equivocada. Y cuando lo encuentro, le hablo primero a él.`,
    excerpt: 'El primer día de facultad me puse la ropa equivocada.',
    thumbnailUrl: 'https://picsum.photos/seed/am-t4/1200/800',
    publishedAt: '2026-01-25T12:00:00.000Z',
    tags: ['identidad', 'educación', 'comunidad'],
    quote: 'Todos estaban igual de perdidos. La diferencia era que ellos podían simular.',
    isDemo: true,
  },
  {
    id: 'demo-texto-5',
    lat: -23.5505,
    lng: -46.6333,
    label: 'La receta que no escribimos',
    title: 'La receta que no escribimos',
    subtitle: 'São Paulo, el sabor que se fue',
    authorName: 'Laura Batista',
    author: { name: 'Laura Batista', avatar: 'https://i.pravatar.cc/150?img=46' },
    city: 'São Paulo',
    country: 'Brasil',
    hasText: true,
    body: `Mi avó hacía un caldo que ninguna de nosotras aprendimos a hacer porque siempre creímos que habría tiempo.

No lo había.

Murió hace muy poco y se llevó la receta con ella. Lo intentamos varias veces: mi madre, mi tía, yo. Cada una recuerda un ingrediente diferente. Ninguna recuerda la proporción. Ninguna recuerda el tiempo de cocción.

Lo más extraño es que cuando alguna vez se acerca, cuando el olor a cebolla y laurel llena la cocina de una manera particular, todas nos miramos sin decir nada. Como si el fantasma del caldo estuviera ahí, entre nosotras, burlándose.

Hay cosas que solo existen mientras existe la persona que las hace. Eso no es una tragedia. Es solo la forma que tiene el amor de dejar espacio.`,
    excerpt:
      'Mi avó hacía un caldo que ninguna de nosotras aprendimos a hacer porque siempre creímos que habría tiempo.',
    thumbnailUrl: 'https://picsum.photos/seed/am-t5/1200/800',
    publishedAt: '2026-01-26T12:00:00.000Z',
    tags: ['familia', 'memoria', 'cuidado'],
    quote: 'Hay cosas que solo existen mientras existe la persona que las hace.',
    isDemo: true,
  },
  {
    id: 'demo-texto-6',
    lat: -0.2299,
    lng: -78.5249,
    label: 'Volver después de diez años',
    title: 'Volver después de diez años',
    subtitle: 'Quito, lo que cambia y lo que no',
    authorName: 'Pablo Andrade',
    author: { name: 'Pablo Andrade', avatar: 'https://i.pravatar.cc/150?img=53' },
    city: 'Quito',
    country: 'Ecuador',
    hasText: true,
    body: `Volví en marzo. El aeropuerto era diferente, más grande, más moderno. La ciudad tenía edificios donde antes había lotes.

Lo primero que hice fue ir al parque donde jugaba de niño. Está igual. Eso me pareció lo más raro de todo: que algo pudiera quedarse exactamente igual mientras yo cambiaba tanto.

Me senté en el mismo banco de siempre. Un chico jugaba en el mismo tobogán de siempre. Por un momento no supe en qué año estaba.

Emigrar te enseña que el tiempo es relativo. Que hay lugares que te esperan y personas que no. Que volver no es lo mismo que regresar. Que el hogar no es un lugar sino un estado que a veces coincide con uno.

Me fui a los veinte. Volví a los treinta. Mañana me voy de nuevo. Esta vez sé que no necesito elegir.`,
    excerpt: 'El aeropuerto era diferente. El parque estaba igual. Eso me pareció lo más raro.',
    thumbnailUrl: 'https://picsum.photos/seed/am-t6/1200/800',
    publishedAt: '2026-01-27T12:00:00.000Z',
    tags: ['migración', 'identidad', 'lugar'],
    quote: 'Volver no es lo mismo que regresar.',
    isDemo: true,
  },
  {
    id: 'demo-texto-7',
    lat: -16.5,
    lng: -68.15,
    label: 'El nombre que me quitaron en la escuela',
    title: 'El nombre que me quitaron en la escuela',
    subtitle: 'La Paz, Wiñaypacha y el castellano',
    authorName: 'Quispe Mamani Luisa',
    author: { name: 'Luisa Quispe', avatar: 'https://i.pravatar.cc/150?img=60' },
    city: 'La Paz',
    country: 'Bolivia',
    hasText: true,
    body: `En mi casa me llaman Wiñaypacha. Significa "tiempo eterno" en aymara.

El primer día de escuela la maestra me preguntó mi nombre. Le dije Wiñaypacha. Me dijo que eso no era un nombre, que me pusiera Luisa.

Tenía seis años. Obedecí.

Durante veinte años respondí a Luisa. Firmé documentos como Luisa. Me presenté como Luisa. Fui Luisa ante personas que nunca supieron que yo era también otra cosa.

A los veintiocho volví a mi comunidad para el funeral de mi abuela. Alguien me llamó Wiñaypacha y me di vuelta sin pensar. Como si ese nombre hubiera estado esperando todo ese tiempo.

Ahora uso los dos. Wiñaypacha Luisa. El orden importa.`,
    excerpt: 'En mi casa me llaman Wiñaypacha. El primer día de escuela me dijeron que eso no era un nombre.',
    thumbnailUrl: 'https://picsum.photos/seed/am-t7/1200/800',
    publishedAt: '2026-01-28T12:00:00.000Z',
    tags: ['identidad', 'política', 'comunidad'],
    quote: 'Ahora uso los dos. El orden importa.',
    isDemo: true,
  },
  {
    id: 'demo-texto-8',
    lat: -33.4489,
    lng: -70.6693,
    label: 'Criar sola y sin manual',
    title: 'Criar sola y sin manual',
    subtitle: 'Santiago, maternidad sin red',
    authorName: 'Daniela Rojas',
    author: { name: 'Daniela Rojas', avatar: 'https://i.pravatar.cc/150?img=37' },
    city: 'Santiago',
    country: 'Chile',
    hasText: true,
    body: `Nadie te dice que criar sola es también un acto político.

Cuando mi hija tenía dos años y yo llegaba a las diez de la noche de trabajar y todavía tenía que hacer la cena y el baño y el cuento y el beso de las buenas noches, no pensaba en política. Pensaba en sobrevivir.

Pero ahora que ella tiene doce y me pregunta cosas, me doy cuenta de lo que le enseñé sin saberlo: que una mujer puede sola. Que pedir ayuda no es debilidad sino inteligencia. Que el cansancio no te define.

Lo que nadie te cuenta es que criar sola también tiene momentos de una libertad particular. Que las decisiones son tuyas. Que el silencio de la noche, cuando ella duerme, es completamente tuyo.

No lo recomiendo. Pero tampoco lo cambiaría.`,
    excerpt: 'Nadie te dice que criar sola es también un acto político.',
    thumbnailUrl: 'https://picsum.photos/seed/am-t8/1200/800',
    publishedAt: '2026-01-29T12:00:00.000Z',
    tags: ['cuidado', 'familia', 'política'],
    quote: 'No lo recomiendo. Pero tampoco lo cambiaría.',
    isDemo: true,
  },
  {
    id: 'demo-texto-9',
    lat: 10.4806,
    lng: -66.9036,
    label: 'Lo que guardé de Venezuela',
    title: 'Lo que guardé de Venezuela',
    subtitle: 'Caracas → Lima, la maleta interior',
    authorName: 'Ernesto Blanco',
    author: { name: 'Ernesto Blanco', avatar: 'https://i.pravatar.cc/150?img=48' },
    city: 'Caracas',
    country: 'Venezuela',
    hasText: true,
    body: `Salí en 2026 con una mochila. Dejé atrás los libros, los muebles, el apartamento donde viví quince años.

Lo que no pude dejar: el acento. La forma de decir "chévere" en el momento equivocado. La costumbre de abrazar a los desconocidos. El olor imaginado del mar de Macuto.

Dicen que la patria es la infancia. Creo que es más específico que eso. La patria es el olor de la cocina de tu madre un domingo. Es el sonido particular del tráfico de tu ciudad a las siete de la mañana. Es algo tan pequeño y tan enorme al mismo tiempo que no tiene nombre.

Llevo meses en Lima. Me gusta. Tiene su propia magia.

Pero a veces, cuando el viento pega de cierta manera, cierro los ojos y estoy en otro lugar.`,
    excerpt: 'Salí en 2026 con una mochila. Lo que no pude dejar: el acento.',
    thumbnailUrl: 'https://picsum.photos/seed/am-t9/1200/800',
    publishedAt: '2026-01-30T12:00:00.000Z',
    tags: ['migración', 'identidad', 'pérdida'],
    quote: 'La patria es el olor de la cocina de tu madre un domingo.',
    isDemo: true,
  },
  {
    id: 'demo-texto-10',
    lat: -2.17,
    lng: -79.9224,
    label: 'Mi padre no llora',
    title: 'Mi padre no llora',
    subtitle: 'Guayaquil, los hombres y el silencio',
    authorName: 'Gabriela Espinosa',
    author: { name: 'Gabriela Espinosa', avatar: 'https://i.pravatar.cc/150?img=26' },
    city: 'Guayaquil',
    country: 'Ecuador',
    hasText: true,
    body: `Mi padre tiene setenta años y nunca lo he visto llorar.

Vi llorar a hombres en el velorio de mi abuelo. Vi llorar a hombres en partidos de fútbol. Vi a mi padre en el velorio de su propio padre: serio, formal, repartiendo abrazos a otros.

Le pregunté una vez. Me dijo: "Los hombres de mi generación aprendimos que llorar era hacerle daño a los demás."

No sé si eso es sabiduría o tragedia. Creo que es las dos cosas.

Lo que sí sé es que mi padre llora de otras maneras. Llora cuando cocina el arroz con leche que hacía mi abuela. Llora cuando me llama el domingo y pregunta cómo estoy con una voz que tiene demasiado en ella.

Hay personas que aprendieron a llorar hacia adentro. A veces pienso que eso duele más.`,
    excerpt: 'Mi padre tiene setenta años y nunca lo he visto llorar.',
    thumbnailUrl: 'https://picsum.photos/seed/am-t10/1200/800',
    publishedAt: '2026-01-31T12:00:00.000Z',
    tags: ['familia', 'cuidado', 'identidad'],
    quote: 'Los hombres de mi generación aprendimos que llorar era hacerle daño a los demás.',
    isDemo: true,
  },
  {
    id: 'demo-texto-11',
    lat: -17.7833,
    lng: -63.1822,
    label: 'Aprender a leer a los cuarenta',
    title: 'Aprender a leer a los cuarenta',
    subtitle: 'Santa Cruz, lo que nadie sabe de mí',
    authorName: 'Don Ramón Suárez',
    author: { name: 'Ramón Suárez', avatar: 'https://i.pravatar.cc/150?img=65' },
    city: 'Santa Cruz',
    country: 'Bolivia',
    hasText: true,
    body: `Tengo cuarenta y tres años y aprendí a leer hace dos.

Toda mi vida tuve estrategias. Pedía a otros que me leyeran los documentos. Memorizaba los colores de los letreros. Fingía que se me había olvidado los anteojos.

Lo que nadie sabe de mí es que durante cuarenta años viví en un mundo que hablaba un idioma que yo no entendía del todo.

Cuando aprendí a leer, lo primero que hice fue leer el nombre de mi calle. Lo sé de memoria, lo había visto mil veces, pero ese día lo leí. Letra por letra.

La segunda cosa fue leer una carta que mi madre me mandó hace veinte años. La había guardado sin abrirla porque no quería pedir ayuda para leerla.

Decía que me quería. Lo sabía. Pero es diferente saberlo a leerlo con tus propios ojos.`,
    excerpt: 'Tengo cuarenta y tres años y aprendí a leer hace dos.',
    thumbnailUrl: 'https://picsum.photos/seed/am-t11/1200/800',
    publishedAt: '2026-02-01T12:00:00.000Z',
    tags: ['educación', 'identidad', 'valentía'],
    quote: 'Lo sabía. Pero es diferente saberlo a leerlo con tus propios ojos.',
    isDemo: true,
  },
  {
    id: 'demo-texto-12',
    lat: -33.4489,
    lng: -70.6693,
    label: 'El año que no salí de casa',
    title: 'El año que no salí de casa',
    subtitle: 'Santiago, salud mental en pandemia',
    authorName: 'Javiera Cortés',
    author: { name: 'Javiera Cortés', avatar: 'https://i.pravatar.cc/150?img=22' },
    city: 'Santiago',
    country: 'Chile',
    hasText: true,
    body: `En 2026 no salí de casa durante nueve meses. No por el virus. Por mí.

Hay dos tipos de encierro: el que te imponen y el que te construís. El mío tenía paredes que solo yo podía ver.

Lo que aprendí es que la recuperación no tiene forma de línea recta. Tiene forma de espiral: vuelves al mismo punto pero un poco más arriba cada vez. A veces no lo notas hasta que miras hacia atrás.

Lo que me salvó fue ridículo y real al mismo tiempo: una planta. Una potus que me regaló mi vecina y que yo casi mato tres veces. Cuidarla me obligó a levantarme todos los días. A recordar que algo dependía de mí.

Todavía la tengo. Lleva tiempo conmigo y ocupa media ventana. La llamo Remedios.`,
    excerpt: 'En 2026 no salí de casa durante nueve meses. No por el virus. Por mí.',
    thumbnailUrl: 'https://picsum.photos/seed/am-t12/1200/800',
    publishedAt: '2026-02-02T12:00:00.000Z',
    tags: ['cuidado', 'salud', 'ciudad'],
    quote: 'La recuperación no tiene forma de línea recta. Tiene forma de espiral.',
    isDemo: true,
  },
];

// ─── FOTOS ───────────────────────────────────────────────────────────────────

export const DEMO_FOTO_STORIES_EXTRA: StoryPoint[] = [
  {
    id: 'demo-foto-2',
    lat: -33.4489,
    lng: -70.6693,
    label: 'El mercado Persa de los domingos',
    title: 'El mercado Persa de los domingos',
    subtitle: 'Santiago, cosas que cambian de dueño',
    authorName: 'Ignacio Pérez',
    author: { name: 'Ignacio Pérez', avatar: 'https://i.pravatar.cc/150?img=55' },
    city: 'Santiago',
    country: 'Chile',
    imagenes: [
      { url: 'https://picsum.photos/seed/am-f2a/1200/900', caption: 'Las mesas del sector de libros, siete de la mañana.' },
      { url: 'https://picsum.photos/seed/am-f2b/1200/900', caption: 'El vendedor de lámparas. Lleva doce años en el mismo puesto.' },
      { url: 'https://picsum.photos/seed/am-f2c/900/1200', caption: 'Lo que alguien dejó ir.' },
      { url: 'https://picsum.photos/seed/am-f2d/1200/900', caption: 'Lo que alguien encontró.' },
    ],
    thumbnailUrl: 'https://picsum.photos/seed/am-f2a/1200/900',
    publishedAt: '2026-02-03T12:00:00.000Z',
    tags: ['ciudad', 'comunidad', 'cotidiano'],
    quote: 'Todo tiene una historia antes de llegar aquí.',
    isDemo: true,
  },
  {
    id: 'demo-foto-3',
    lat: 17.0732,
    lng: -96.7266,
    label: 'Mujeres de Tehuantepec',
    title: 'Mujeres de Tehuantepec',
    subtitle: 'Oaxaca, el matriarcado cotidiano',
    authorName: 'Fernanda Ruiz',
    author: { name: 'Fernanda Ruiz', avatar: 'https://i.pravatar.cc/150?img=31' },
    city: 'Tehuantepec',
    country: 'México',
    imagenes: [
      { url: 'https://picsum.photos/seed/am-f3a/1200/900', caption: 'Doña Petra en su puesto del mercado, cinco de la mañana.' },
      { url: 'https://picsum.photos/seed/am-f3b/900/1200', caption: 'El traje de tehuana que se pone los domingos.' },
      { url: 'https://picsum.photos/seed/am-f3c/1200/900', caption: 'Sus hijas, que aprendieron el oficio.' },
      { url: 'https://picsum.photos/seed/am-f3d/1200/900', caption: 'La nieta que todavía no sabe que lo heredará.' },
      { url: 'https://picsum.photos/seed/am-f3e/1200/900', caption: 'El mercado desde adentro.' },
    ],
    thumbnailUrl: 'https://picsum.photos/seed/am-f3a/1200/900',
    publishedAt: '2026-02-04T12:00:00.000Z',
    tags: ['comunidad', 'trabajo', 'identidad'],
    quote: 'El poder aquí no se anuncia. Se ejerce.',
    isDemo: true,
  },
  {
    id: 'demo-foto-4',
    lat: -34.6037,
    lng: -58.3816,
    label: 'Villa 31, lo que construimos',
    title: 'Villa 31, lo que construimos',
    subtitle: 'Buenos Aires, una arquitectura propia',
    authorName: 'Marcos Villalba',
    author: { name: 'Marcos Villalba', avatar: 'https://i.pravatar.cc/150?img=19' },
    city: 'Buenos Aires',
    country: 'Argentina',
    imagenes: [
      { url: 'https://picsum.photos/seed/am-f4a/1200/900', caption: 'La muralla pintada por los chicos del barrio.' },
      { url: 'https://picsum.photos/seed/am-f4b/1200/900', caption: 'La escalera que construyó el vecino sin planos.' },
      { url: 'https://picsum.photos/seed/am-f4c/900/1200', caption: 'Vista desde arriba.' },
      { url: 'https://picsum.photos/seed/am-f4d/1200/900', caption: 'El comedor comunitario, doce del mediodía.' },
    ],
    thumbnailUrl: 'https://picsum.photos/seed/am-f4a/1200/900',
    publishedAt: '2026-02-05T12:00:00.000Z',
    tags: ['ciudad', 'comunidad', 'política'],
    quote: 'Nadie nos preguntó cómo queríamos vivir. Lo decidimos solos.',
    isDemo: true,
  },
  {
    id: 'demo-foto-5',
    lat: -13.532,
    lng: -71.9675,
    label: 'El tejido que habla',
    title: 'El tejido que habla',
    subtitle: 'Cusco, quipus y memorias',
    authorName: 'Marcelina Ccoa',
    author: { name: 'Marcelina Ccoa', avatar: 'https://i.pravatar.cc/150?img=42' },
    city: 'Cusco',
    country: 'Perú',
    imagenes: [
      { url: 'https://picsum.photos/seed/am-f5a/1200/900', caption: 'El telar que tiene mi familia desde tres generaciones.' },
      { url: 'https://picsum.photos/seed/am-f5b/900/1200', caption: 'Cada color tiene un significado.' },
      { url: 'https://picsum.photos/seed/am-f5c/1200/900', caption: 'Mi madre enseñando a mi sobrina.' },
      { url: 'https://picsum.photos/seed/am-f5d/1200/900', caption: 'El tejido terminado cuenta una historia.' },
      { url: 'https://picsum.photos/seed/am-f5e/900/1200', caption: 'Lo que mis manos saben que mi boca no puede decir.' },
    ],
    thumbnailUrl: 'https://picsum.photos/seed/am-f5a/1200/900',
    publishedAt: '2026-02-06T12:00:00.000Z',
    tags: ['identidad', 'comunidad', 'arte'],
    quote: 'Mis manos saben cosas que mi boca no puede decir.',
    isDemo: true,
  },
  {
    id: 'demo-foto-6',
    lat: -23.5505,
    lng: -46.6333,
    label: 'Noite na Cracolândia',
    title: 'Noite na Cracolândia',
    subtitle: 'São Paulo, lo que la ciudad no quiere ver',
    authorName: 'Thiago Souza',
    author: { name: 'Thiago Souza', avatar: 'https://i.pravatar.cc/150?img=56' },
    city: 'São Paulo',
    country: 'Brasil',
    imagenes: [
      { url: 'https://picsum.photos/seed/am-f6a/1200/900', caption: 'Las tres de la mañana.' },
      { url: 'https://picsum.photos/seed/am-f6b/1200/900', caption: 'El hombre que todos los días trae agua.' },
      { url: 'https://picsum.photos/seed/am-f6c/900/1200', caption: 'Un abrazo.' },
      { url: 'https://picsum.photos/seed/am-f6d/1200/900', caption: 'El amanecer llega igual.' },
    ],
    thumbnailUrl: 'https://picsum.photos/seed/am-f6a/1200/900',
    publishedAt: '2026-02-07T12:00:00.000Z',
    tags: ['ciudad', 'cuidado', 'política'],
    quote: 'Estas personas tienen nombres. Yo los aprendí.',
    isDemo: true,
  },
  {
    id: 'demo-foto-7',
    lat: -39.8142,
    lng: -73.2459,
    label: 'El bosque después del incendio',
    title: 'El bosque después del incendio',
    subtitle: 'Sur de Chile, lo que vuelve a crecer',
    authorName: 'Roberto Mansilla',
    author: { name: 'Roberto Mansilla', avatar: 'https://i.pravatar.cc/150?img=62' },
    city: 'Valdivia',
    country: 'Chile',
    imagenes: [
      { url: 'https://picsum.photos/seed/am-f7a/1200/900', caption: 'Enero de 2026, tres días después.' },
      { url: 'https://picsum.photos/seed/am-f7b/1200/900', caption: 'Marzo, los primeros brotes.' },
      { url: 'https://picsum.photos/seed/am-f7c/1200/900', caption: 'Agosto, lo que sobrevivió.' },
      { url: 'https://picsum.photos/seed/am-f7d/900/1200', caption: 'Diciembre, el bosque recuerda.' },
    ],
    thumbnailUrl: 'https://picsum.photos/seed/am-f7a/1200/900',
    publishedAt: '2026-02-08T12:00:00.000Z',
    tags: ['naturaleza', 'memoria', 'lugar'],
    quote: 'Lo que quema también prepara el suelo para lo que viene.',
    isDemo: true,
  },
  {
    id: 'demo-foto-8',
    lat: 4.711,
    lng: -74.0721,
    label: 'Los lunes en el Transmilenio',
    title: 'Los lunes en el Transmilenio',
    subtitle: 'Bogotá, retratos de la hora pico',
    authorName: 'Carolina Mejía',
    author: { name: 'Carolina Mejía', avatar: 'https://i.pravatar.cc/150?img=34' },
    city: 'Bogotá',
    country: 'Colombia',
    imagenes: [
      { url: 'https://picsum.photos/seed/am-f8a/1200/900', caption: 'La señora que siempre lleva flores.' },
      { url: 'https://picsum.photos/seed/am-f8b/1200/900', caption: 'Dos personas que no se conocen, dormidas.' },
      { url: 'https://picsum.photos/seed/am-f8c/900/1200', caption: 'El niño que le cedió el asiento a un anciano.' },
      { url: 'https://picsum.photos/seed/am-f8d/1200/900', caption: 'Seis y media de la mañana.' },
      { url: 'https://picsum.photos/seed/am-f8e/1200/900', caption: 'Lo que se lleva cada uno al trabajo.' },
    ],
    thumbnailUrl: 'https://picsum.photos/seed/am-f8a/1200/900',
    publishedAt: '2026-02-09T12:00:00.000Z',
    tags: ['ciudad', 'cotidiano', 'comunidad'],
    quote: 'En el bus todos somos iguales por un momento.',
    isDemo: true,
  },
  {
    id: 'demo-foto-9',
    lat: -16.5,
    lng: -68.15,
    label: 'El carnaval de mi pueblo',
    title: 'El carnaval de mi pueblo',
    subtitle: 'Oruro, los colores que no se olvidan',
    authorName: 'Yolanda Mamani',
    author: { name: 'Yolanda Mamani', avatar: 'https://i.pravatar.cc/150?img=28' },
    city: 'Oruro',
    country: 'Bolivia',
    imagenes: [
      { url: 'https://picsum.photos/seed/am-f9a/1200/900', caption: 'Los preparativos empiezan en enero.' },
      { url: 'https://picsum.photos/seed/am-f9b/900/1200', caption: 'El traje que tardó ocho meses en hacerse.' },
      { url: 'https://picsum.photos/seed/am-f9c/1200/900', caption: 'La danza del diablo.' },
      { url: 'https://picsum.photos/seed/am-f9d/1200/900', caption: 'Mi abuela viendo desde la vereda.' },
    ],
    thumbnailUrl: 'https://picsum.photos/seed/am-f9a/1200/900',
    publishedAt: '2026-02-10T12:00:00.000Z',
    tags: ['comunidad', 'identidad', 'arte'],
    quote: 'Bailamos para recordar de dónde venimos.',
    isDemo: true,
  },
  {
    id: 'demo-foto-10',
    lat: -0.2299,
    lng: -78.5249,
    label: 'El páramo a cuatro mil metros',
    title: 'El páramo a cuatro mil metros',
    subtitle: 'Cotopaxi, la niebla que habita',
    authorName: 'Diego Cárdenas',
    author: { name: 'Diego Cárdenas', avatar: 'https://i.pravatar.cc/150?img=66' },
    city: 'Cotopaxi',
    country: 'Ecuador',
    imagenes: [
      { url: 'https://picsum.photos/seed/am-f10a/1200/900', caption: 'El volcán en un día sin nubes. Ocurre tres veces al año.' },
      { url: 'https://picsum.photos/seed/am-f10b/1200/900', caption: 'La comunidad que cuida el agua.' },
      { url: 'https://picsum.photos/seed/am-f10c/900/1200', caption: 'El frailejón, que crece un centímetro por año.' },
      { url: 'https://picsum.photos/seed/am-f10d/1200/900', caption: 'La neblina que lo cubre todo.' },
    ],
    thumbnailUrl: 'https://picsum.photos/seed/am-f10a/1200/900',
    publishedAt: '2026-02-11T12:00:00.000Z',
    tags: ['naturaleza', 'comunidad', 'lugar'],
    quote: 'El páramo no se visita. Se habita o se pasa de largo.',
    isDemo: true,
  },
  {
    id: 'demo-foto-11',
    lat: -32.9442,
    lng: -60.6505,
    label: 'Retratos de la calle Paraguay',
    title: 'Retratos de la calle Paraguay',
    subtitle: 'Rosario, quiénes viven aquí',
    authorName: 'Sofía Almada',
    author: { name: 'Sofía Almada', avatar: 'https://i.pravatar.cc/150?img=40' },
    city: 'Rosario',
    country: 'Argentina',
    imagenes: [
      { url: 'https://picsum.photos/seed/am-f11a/1200/900', caption: 'El kiosco que lleva treinta años abierto.' },
      { url: 'https://picsum.photos/seed/am-f11b/900/1200', caption: 'Don Jorge, que conoce a todos por nombre.' },
      { url: 'https://picsum.photos/seed/am-f11c/1200/900', caption: 'Los chicos que juegan en la esquina.' },
      { url: 'https://picsum.photos/seed/am-f11d/1200/900', caption: 'La calle a las once de la noche.' },
    ],
    thumbnailUrl: 'https://picsum.photos/seed/am-f11a/1200/900',
    publishedAt: '2026-02-12T12:00:00.000Z',
    tags: ['ciudad', 'comunidad', 'cotidiano'],
    quote: 'Una calle es también una forma de vivir juntos.',
    isDemo: true,
  },
  {
    id: 'demo-foto-12',
    lat: -12.0464,
    lng: -77.0428,
    label: 'El mar desde Villa María del Triunfo',
    title: 'El mar desde Villa María del Triunfo',
    subtitle: 'Lima, el mar que no siempre se ve',
    authorName: 'Patricia Quispe',
    author: { name: 'Patricia Quispe', avatar: 'https://i.pravatar.cc/150?img=20' },
    city: 'Lima',
    country: 'Perú',
    imagenes: [
      { url: 'https://picsum.photos/seed/am-f12a/1200/900', caption: 'Desde el cerro, en días claros, se ve el Pacífico.' },
      { url: 'https://picsum.photos/seed/am-f12b/1200/900', caption: 'Mi hijo viendo el mar por primera vez.' },
      { url: 'https://picsum.photos/seed/am-f12c/900/1200', caption: 'La neblina que lo tapa casi siempre.' },
      { url: 'https://picsum.photos/seed/am-f12d/1200/900', caption: 'El barrio frente al océano que nunca baja.' },
    ],
    thumbnailUrl: 'https://picsum.photos/seed/am-f12a/1200/900',
    publishedAt: '2026-02-13T12:00:00.000Z',
    tags: ['ciudad', 'naturaleza', 'comunidad'],
    quote: 'Vivimos a media hora del mar y tardé diez años en llevarlo.',
    isDemo: true,
  },
] as unknown as StoryPoint[];
