/**
 * Contenido legacy de Política Digital (forma cruda).
 * Sustituir este array por la importación real del sitio antiguo cuando esté disponible.
 * Cada objeto debe tener al menos: id, slug, title, excerpt, date; opcional: category, type, section, featured, hero, image, content, modified, sourceName, sourceUrl.
 */

export type LegacyPostShape = Record<string, unknown>;

export const LEGACY_POLITICA_DIGITAL_POSTS: LegacyPostShape[] = [
  {
    id: 'pd-1',
    slug: 'gobierno-digital-cdmx',
    title: 'Gobierno digital en la CDMX: avances y retos',
    excerpt: 'Un repaso por las iniciativas de innovación pública y servicios digitales en la Ciudad de México.',
    date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString().slice(0, 10),
    category: 'Experiencia',
    featured: true,
    hero: true,
    content: '',
    sourceName: 'Política Digital',
  },
  {
    id: 'pd-2',
    slug: 'senal-datos-abiertos-jalisco',
    title: 'Jalisco abre nuevos conjuntos de datos abiertos',
    excerpt: 'El estado publica datos de transparencia y servicios públicos en formato reutilizable.',
    date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString().slice(0, 10),
    category: 'Señal',
    featured: true,
    content: '',
    sourceName: 'Política Digital',
  },
  {
    id: 'pd-3',
    slug: 'norma-ia-sector-publico',
    title: 'Nueva norma sobre uso de inteligencia artificial en el sector público',
    excerpt: 'Lineamientos para la adopción de IA en gobierno con enfoque en derechos y transparencia.',
    date: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString().slice(0, 10),
    type: 'norma',
    featured: true,
    content: '',
    sourceName: 'Política Digital',
  },
  {
    id: 'pd-4',
    slug: 'analisis-gobierno-digital-mexico',
    title: 'Análisis: el estado del gobierno digital en México',
    excerpt: 'Opinión sobre innovación pública, datos y servicios públicos en la región.',
    date: new Date(Date.now() - 21 * 24 * 60 * 60 * 1000).toISOString().slice(0, 10),
    section: 'Análisis',
    featured: true,
    content: '',
    sourceName: 'Política Digital',
  },
  {
    id: 'pd-5',
    slug: 'experiencia-nuevo-leon-servicios',
    title: 'Nuevo León: experiencia en servicios públicos digitales',
    excerpt: 'Cómo el estado ha mejorado la atención ciudadana con gobierno digital.',
    date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString().slice(0, 10),
    category: 'Experiencia',
    featured: true,
    content: '',
    sourceName: 'Política Digital',
  },
  {
    id: 'pd-6',
    slug: 'senal-licitacion-veracruz',
    title: 'Veracruz: licitación para plataforma de trámites',
    excerpt: 'Señal reciente sobre compra pública de tecnología en Veracruz.',
    date: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString().slice(0, 10),
    category: 'Señal',
    type: 'licitacion',
    featured: false,
    content: '',
    sourceName: 'Política Digital',
  },
  {
    id: 'pd-7',
    slug: 'programa-datos-abiertos-puebla',
    title: 'Programa de datos abiertos en Puebla',
    excerpt: 'Iniciativa de innovación pública y transparencia en el estado.',
    date: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString().slice(0, 10),
    type: 'programa',
    featured: true,
    content: '',
    sourceName: 'Política Digital',
  },
  {
    id: 'pd-8',
    slug: 'experiencia-yucatan-gobierno-digital',
    title: 'Yucatán: gobierno digital y servicios públicos',
    excerpt: 'Experiencia estatal en digitalización de trámites y atención ciudadana.',
    date: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString().slice(0, 10),
    category: 'Experiencia',
    featured: true,
    content: '',
    sourceName: 'Política Digital',
  },
];
