/**
 * Historias en video de demostración para /historias/videos.
 * Cada archivo en public/ con video debe tener una entrada aquí para verse en CinemaGallery.
 * Se fusionan con las historias con video de la API (ver page.tsx).
 */
import type { StoryPoint } from '@/lib/map-data/stories';

/** Nombre con espacios → ruta segura en el navegador */
const HUMANOID_COPY = '/6995093_Humanoid_Bot_3840x2160%20(1).mp4';

export const DEMO_VIDEO_STORIES: (StoryPoint & { isDemo?: boolean })[] = [
  {
    id: 'demo-video-1',
    lat: -33.4489,
    lng: -70.6693,
    label: 'Santiago',
    title: 'El mundo desde aquí',
    authorName: 'María',
    city: 'Santiago',
    country: 'Chile',
    videoUrl: '/Earth_wAtmos_spin_02_1080p60.mp4',
    hasVideo: true,
    publishedAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    isDemo: true,
  },
  {
    id: 'demo-video-2',
    lat: -34.6037,
    lng: -58.3816,
    label: 'Buenos Aires',
    title: 'Una ventana al planeta',
    authorName: 'Carlos',
    city: 'Buenos Aires',
    country: 'Argentina',
    videoUrl: '/Earth_wAtmos_spin_02_1080p60.mp4',
    hasVideo: true,
    publishedAt: new Date(Date.now() - 86400000 * 5).toISOString(),
    isDemo: true,
  },
  {
    id: 'demo-video-3',
    lat: 40.7128,
    lng: -74.006,
    label: 'New York',
    title: 'Historias en movimiento',
    authorName: 'Ana',
    city: 'New York',
    country: 'Estados Unidos',
    videoUrl: '/earth-blue-marble-720p-60fps.mp4',
    hasVideo: true,
    publishedAt: new Date(Date.now() - 86400000 * 10).toISOString(),
    isDemo: true,
  },
  {
    id: 'demo-video-4',
    lat: 19.4326,
    lng: -99.1332,
    label: 'Ciudad de México',
    title: 'Lo que veo desde mi ciudad',
    authorName: 'Luis',
    city: 'Ciudad de México',
    country: 'México',
    videoUrl: '/earth-globe-nasa.mp4',
    hasVideo: true,
    publishedAt: new Date(Date.now() - 86400000 * 15).toISOString(),
    isDemo: true,
  },
  {
    id: 'demo-video-5',
    lat: 40.4168,
    lng: -3.7038,
    label: 'Madrid',
    title: 'Un lugar en el mundo',
    authorName: 'Elena',
    city: 'Madrid',
    country: 'España',
    videoUrl: '/earth-blue-marble-720p.mp4',
    hasVideo: true,
    publishedAt: new Date(Date.now() - 86400000 * 20).toISOString(),
    isDemo: true,
  },
  {
    id: 'demo-video-6',
    lat: 51.5074,
    lng: -0.1278,
    label: 'Londres',
    title: 'Mi historia en video',
    authorName: 'Sofia',
    city: 'Londres',
    country: 'Reino Unido',
    videoUrl: '/a002709.webmhd.webm',
    hasVideo: true,
    publishedAt: new Date(Date.now() - 86400000 * 1).toISOString(),
    isDemo: true,
  },
  {
    id: 'demo-video-7',
    lat: -23.5505,
    lng: -46.6333,
    label: 'São Paulo',
    title: 'Otra historia para probar',
    authorName: 'Ricardo',
    city: 'São Paulo',
    country: 'Brasil',
    videoUrl: '/0_Man_Person_3840x2160.mp4',
    hasVideo: true,
    publishedAt: new Date(Date.now() - 86400000 * 3).toISOString(),
    isDemo: true,
  },
  {
    id: 'demo-video-8',
    lat: 35.6762,
    lng: 139.6503,
    label: 'Tokyo',
    title: 'Una más en la galería',
    authorName: 'Yuki',
    city: 'Tokyo',
    country: 'Japón',
    videoUrl: '/6994253_Generative_Female_Ceo_3840x2160.mp4',
    hasVideo: true,
    publishedAt: new Date(Date.now() - 86400000 * 7).toISOString(),
    isDemo: true,
  },
  {
    id: 'demo-video-9',
    lat: 48.2082,
    lng: 16.3738,
    label: 'Viena',
    title: 'Tierra en alta definición',
    authorName: 'Thomas',
    city: 'Viena',
    country: 'Austria',
    videoUrl: '/earth-1080p60.mp4',
    hasVideo: true,
    publishedAt: new Date(Date.now() - 86400000 * 4).toISOString(),
    isDemo: true,
  },
  {
    id: 'demo-video-10',
    lat: 59.3293,
    lng: 18.0686,
    label: 'Estocolmo',
    title: 'Rotación suave',
    authorName: 'Elin',
    city: 'Estocolmo',
    country: 'Suecia',
    videoUrl: '/rotate_hd_1280_lossless.mp4',
    hasVideo: true,
    publishedAt: new Date(Date.now() - 86400000 * 6).toISOString(),
    isDemo: true,
  },
  {
    id: 'demo-video-11',
    lat: 1.3521,
    lng: 103.8198,
    label: 'Singapur',
    title: 'Demo humanoide',
    authorName: 'Wei',
    city: 'Singapur',
    country: 'Singapur',
    videoUrl: '/6995093_Humanoid_Bot_3840x2160.mp4',
    hasVideo: true,
    publishedAt: new Date(Date.now() - 86400000 * 8).toISOString(),
    isDemo: true,
  },
  {
    id: 'demo-video-12',
    lat: 22.3193,
    lng: 114.1694,
    label: 'Hong Kong',
    title: 'Humanoid (copia)',
    authorName: 'Ming',
    city: 'Hong Kong',
    country: 'China',
    videoUrl: HUMANOID_COPY,
    hasVideo: true,
    publishedAt: new Date(Date.now() - 86400000 * 9).toISOString(),
    isDemo: true,
  },
];
